name: Build Karing Archives

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полный клон репо

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create directories
      run: |
        mkdir -p Karing light dark
        ls -R  # Отладка: структура папок

    - name: Clean temp directories
      run: |
        rm -rf light/* dark/*  # Очищаем light и dark перед копированием

    - name: Modify settings for light
      run: |
        python -c "
        import json
        with open('Karing/files/karing_setting.json', 'r') as f:
          data = json.load(f)
        data['ui_screen'] = {
          'widgets': [
            'run_time_info', 'connections_info', 'traffic_total_info', 'traffic_speed_info',
            'profile_sub_traffic_info', 'system_proxy', 'my_profiles', 'add_profile',
            'diversion_rules', 'perapp', 'net_check', 'speed_test', 'dns', 'my_link'
          ],
          'widgets_alpha': 255,
          'hide_invalid_server_my_profiles': False,
          'hide_invalid_server_select_server': False,
          'hide_invalid_server_diversion_rules': False,
          'sort_server_my_profiles': False,
          'sort_server_select_server': False,
          'sort_server_diversion_rules': False,
          'select_server_hide_recommand': False,
          'select_server_hide_recent': False,
          'select_server_hide_fav': False,
          'hide_unused_diversion_group': False,
          'my_link': 'https://t.me/FIVEHEADVPNbot',
          'background_image_type': 'remote',
          'background_image': 'https://raw.githubusercontent.com/gfreemoon/vat_repo/refs/heads/main/Karing/background.png',
          'background_image_local': ''
        }
        with open('light/karing_setting.json', 'w') as f:
          json.dump(data, f, indent=2)
        "

    - name: Modify settings for dark
      run: |
        python -c "
        import json
        with open('Karing/files/karing_setting.json', 'r') as f:
          data = json.load(f)
        data['ui_screen'] = {
          'widgets': [
            'run_time_info', 'connections_info', 'traffic_total_info', 'traffic_speed_info',
            'profile_sub_traffic_info', 'system_proxy', 'my_profiles', 'add_profile',
            'diversion_rules', 'perapp', 'net_check', 'speed_test', 'dns', 'my_link'
          ],
          'widgets_alpha': 255,
          'hide_invalid_server_my_profiles': False,
          'hide_invalid_server_select_server': False,
          'hide_invalid_server_diversion_rules': False,
          'sort_server_my_profiles': False,
          'sort_server_select_server': False,
          'sort_server_diversion_rules': False,
          'select_server_hide_recommand': False,
          'select_server_hide_recent': False,
          'select_server_hide_fav': False,
          'hide_unused_diversion_group': False,
          'my_link': 'https://t.me/FIVEHEADVPNbot',
          'background_image_type': 'remote',
          'background_image': 'https://raw.githubusercontent.com/gfreemoon/vat_repo/refs/heads/main/Karing/bg_dark.png',
          'background_image_local': ''
        }
        with open('dark/karing_setting.json', 'w') as f:
          json.dump(data, f, indent=2)
        "

    - name: Copy common files to light
      run: |
        cp Karing/files/karing_routing_group.json light/
        cp Karing/files/karing_subscribe.json light/
        cp Karing/files/karing_subscribe_use.json light/
        ls -l light/  # Отладка: содержимое light

    - name: Copy common files to dark
      run: |
        cp Karing/files/karing_routing_group.json dark/
        cp Karing/files/karing_subscribe.json dark/
        cp Karing/files/karing_subscribe_use.json dark/
        ls -l dark/  # Отладка: содержимое dark

    - name: Build ZIPs
      run: |
        cd light && zip -r ../Karing/5head_Karing.backup.zip .
        cd ../dark && zip -r ../Karing/5head_Karing_dark.backup.zip .
        ls -l Karing/  # Отладка: содержимое Karing

    - name: Commit and push ZIPs
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add Karing/*.zip
        git status  # Отладка: что добавлено в коммит
        git commit -m 'Auto-build Karing archives' || echo 'No changes to commit'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
